name: Laravel Local
values:
  - key: base_url
    value: 'http://localhost'
    type: default
    enabled: true
  - key: token
    value: ''
    type: secret
    enabled: true
  - key: post_id
    value: '1'
    type: default
    enabled: true
  - key: comment_id
    value: '1'
    type: default
    enabled: true
